module.exports = 

'Uptown': [
  'Lenox Hill'
  'Lincoln Square'
  'UES'
  'UWS'
  'East Harlem'
  'Fort George'
  'Hamilton Heights'
  'Harlem'
  'Inwood'
  'Upper Manhattan'
  'Washington Heights'
  'Yorkville'
  'Hudson Heights'
  'Central Park'
]
'Midtown': [
  'Chelsea'
  'Gramercy Park'
  "Hell's Kitchen"
  'Kips Bay'
  'Midtown'
  'Turtle Bay'
  'Korea Town'
  'Sutton Place'
  'Union Square'
  'Theater District - Times Square'
  'NoMad'
  'Stuyvesant Town'
]
'Downtown': [
  'Lower Manhattan'
  'Alphabet City'
  'Downtown'
  'East Village'
  'Greenwich Village'
  'Lower East Side'
  'NoLita'
  'South Side'
  'World Trade Center'
  'Bowery'
  'Chinatown'
  'Little Italy'
]
'South Brooklyn': [
  'Clinton Hill'
  'Crown Heights'
  'Downtown Brooklyn'
  'Sheepshead Bay'
  'Brooklyn Heights'
  'East Flatbush'
  'East New York'
  'Fort Greene'
  'Vinegar Hill'
  'Bay Ridge'
  'Carroll Gardens'
  'Flatbush - Ditmas Park'
  'Greenwood'
  'Park Slope'
  'Sunset Park'
  'Prospect Lefferts Gardens'
  'Bergen Beach'
  'Canarsie'
  'Kensington & Parkville'
  'Little Neck'
  'Midwood'
  'Prospect Heights'
  'South Slope'
  'Windsor Terrace'
]
'North Brooklyn': [
  'Bushwick'
  'Williamsburg'
  'Bedford-Stuyvesant'
  'Dumbo'
  'East Williamsburg'
  'Greenpoint'
]
'Queens': [
  'LIC'
  'Roosevelt Island'
  'Astoria'
  'Hunters Point'
  'Bayside'
  'Elmhurst'
  'Flushing'
  'Jamaica'
  'Middle Village'
  'Corona'
  'Forest Hills'
  'Kew Gardens'
  'Kew Gardens Hills'
  'Far Rockaway'
  'Malba'
  'Queens Village'
  'Rego Park'
  'Richmond Hill'
  'Ridgewood'
  'St. Albans'
  'Sunnyside'
  'Whitestone'
]
'Bronx': [
  'Kingsbridge'
  'Mott Haven'
  'Concourse'
  'Morris Heights'
  'Claremont'
  'Highbridge'
  'Jerome Park'
  'Norwood'
  'Parkchester'
  'Riverdale'
  'University Heights'
  'West Bronx'
]
'Staten Island': [
  'Park Hill'
  'St. George'
]